# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d482f1e55e85ef284d111f12f79a354f15222e935274399bf04e96b9db995dc4a67df590206a5d1198ba7e632010b6b863b0606a40f85a400cb496062e4697e

test:
  secret_key_base: ffd36c92519e57139381343feac280adc5b5015c0b8613c95966e39a1f1bdb66d8fc9da679ceefb44c17b9c071048d1f871706491a394ef8f2c0ef150cd5b8c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
